language: dart
sudo: false
dart:
  - stable
dart_task:
  - test: --platform vm
  - test: --platform firefox -j 1
  - dartanalyzer: --fatal-warnings --fatal-lints lib
cache:
  directories:
    - $HOME/.pub-cache